version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
      AIRFLOW_CONN_OPEN_METEO_API: https://api.open-meteo.com
    ports:
      - "8080:8080"
    command: webserver

volumes:
  postgres_data: